name: Development

on:
  push:
    branches: "development"    
  workflow_dispatch:
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: development
    - uses: azure/docker-login@v2
      with:
        login-server: moodleapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        version=$(git rev-parse --short HEAD)
        docker build -t moodleapp.azurecr.io/moodle-appservice:development-$version .
        docker push moodleapp.azurecr.io/moodle-appservice:development-$version

  deploy:
        runs-on: ubuntu-latest
        needs: build-dev
        environment:
                name: 'development'
                url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        steps:
                - name: Lowercase the repo name
                  run: echo "REPO=${https://github.com/xcorpo/moodle-appservice}" >>${GITHUB_ENV}
          
                - name: Deploy to Azure Web App
                  id: deploy-to-webapp
                  uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
                  with:
                    app-name: ${{ env.AZURE_WEBAPP_NAME }}
                    publish-profile: ${{ secrets.DEV_STAGING_PROFILE }}
                    images: 'moodleapp/${{ env.REPO }}:${{ github.sha }}'