name: Development

on:
  push:
    branches: "development"    
  workflow_dispatch:
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: development
    - uses: azure/docker-login@v2
      with:
        login-server: moodleapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        version=$(git rev-parse --short HEAD)
        docker build -t moodleapp.azurecr.io/moodle-appservice:development-$version .
        docker push moodleapp.azurecr.io/moodle-appservice:development-$version

  deploy:
      runs-on: ubuntu-latest
      needs: build-dev
      environment:
        name: 'moodleenfra'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'moodleenfra(stage)'
            slot-name: 'stage'
            publish-profile: ${{ secrets.DEV_STAGING_PROFILE }}
            images: 'moodleapp.azurecr.io/moodle-appservice:${{ github.sha }}'