name: Production

on:
  pull_request:
    branches: "production"
  workflow_dispatch:     
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: production
    - uses: azure/docker-login@v2
      with:
        login-server: moodleapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -t moodleapp.azurecr.io/moodle-appservice:production-${{ github.sha }} .
        docker push moodleapp.azurecr.io/moodle-appservice:production-${{ github.sha }}

  deploy:
        runs-on: ubuntu-latest
        needs: build-prod
        environment:
                name: 'production'
                url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        steps:
                - name: Lowercase the repo name
                  run: echo "REPO=${https://github.com/xcorpo/moodle-appservice}" >>${GITHUB_ENV}
          
                - name: Deploy to Azure Web App
                  id: deploy-to-webapp
                  uses: azure/webapps-deploy@v2
                  with:
                    app-name: ${{ env.AZURE_WEBAPP_NAME }}
                    publish-profile: ${{ secrets.PROD_PROFILE }}
                    images: 'moodleapp.azurecr.io/moodle-appservice:production-${{ github.sha }}'