name: Production

on:
  pull_request:
    branches: [ "production" ]    
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Git Pull Latest Repo
      run: git pull
    - name: Checkout to production branch
      run: git checkout production
    - uses: azure/docker-login@v2
      with:
        login-server: moodleapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        version=$(git rev-parse --short HEAD)
        docker build -t moodleapp.azurecr.io/moodle-appservice:production .
        docker push moodleapp.azurecr.io/moodle-appservice:production

